modLoader = "javafml" #mandatory
loaderVersion = "${loader_version}" #mandatory
license = "Creative Commons"
issueTrackerURL = "${git_url}/issues" #optional
[[mods]] #mandatory
modId = "exnihiloae" #mandatory
version = "${version}" #mandatory
displayName = "Ex Nihilo: Sequentia - AE2 Addon" #mandatory
displayURL = "${curseforge_url}" #optional
logoFile = "logo.png" #optional
credits = "" #optional
authors = "NovaMachina" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
    An addon for Ex Nihilo: Sequentia that adds support for Applied Energistics 2.
    '''
[[dependencies.exnihiloae]]
modId = "exnihilosequentia"
mandatory = true
versionRange = "${ex_nihilo_version}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.exnihiloae]]
modId = "ae2"
mandatory = true
versionRange = "${ae2_version}"
ordering = "AFTER"
side = "BOTH"
